/** Auto-generated by scripts/build_category_pages.py — do not edit by hand. */
export const SECTION_SLUGS = {
    builds: 'builds',
    uniques: 'unique',
    runes: 'runewords',
    cubing: 'cube',
    runelist: 'runes',
    merc: 'mercenary',
    frame: 'frames',
    leveling: 'leveling',
    dropcalc: 'magic-find',
    ladder: 'patches',
    charms: 'sunder',
    uber: 'uber',
    quest: 'quests',
    bus: 'bus',
    farming: 'farming',
};

export const SLUG_SECTIONS = Object.fromEntries(
    Object.entries(SECTION_SLUGS).map(([section, slug]) => [slug, section])
);

export function sectionPath(sectionId, lang = (typeof window !== 'undefined' && window.SITE_LANG) || 'ko') {
    const slug = SECTION_SLUGS[sectionId];
    if (!slug) return lang === 'en' ? '/en/' : '/';
    return lang === 'en' ? `/en/${slug}/` : `/${slug}/`;
}

export function sectionFromPath(pathname = typeof location !== 'undefined' ? location.pathname : '/') {
    const p = String(pathname || '/').replace(/\/index\.html$/i, '/');
    const m = p.match(/^\/(en\/)?([^/]+)\/?$/);
    if (!m || !m[2]) return null;
    return SLUG_SECTIONS[m[2]] || null;
}

